### ISSUE TITLE
Where can I find the roadmap of jhipster-go ?

### ISSUE THREAD

**Issue by yangyanqing** [jhipster/jhipster-go#4]
JHipster-java is a very excellent tools which provides a fast-way and lots of best practice !
Now I am really looking forward to jhipster-go, but can't find the roadmap :(

**Comment by deepu105** [comment]
There isn't ome yet. I still have to make a first version. Hopefully sometime this year but nothing is promised

**Comment by yangyanqing** [comment]
Thanks for your reply !
And when will the first version be released ? :)

**Comment by deepu105** [comment]
No idea honestly. Depends on when I have time

**Comment by yangyanqing** [comment]
I'm interested in this project, and might give a hand to you.
